### ISSUE TITLE
Tasks Checklist

### ISSUE THREAD

**Issue by sidntrivedi012** [Crypt0knights/Plagiarism-Detector#2]
- [x] Upload pdf
- [x] Convert pdf to text
- [x] Apply NLP to the text extracted.
- [x] Use the text generated after applying NLP in the API
- [x] Query the API
- [x] Visualise the API data received
- [x] Display top 5 matched links

**Comment by nightwarrior-xxx** [comment]
@sidntrivedi012  @code-monk08  
```
25 credits / month
6,250 words / month
2 concurrent scans
Low priority
```
Thats what the copy leaks free plan says. What does concurrent scans means ? And is it we have only 2 scans possible ? I have made an account on it and will continue at night . Going Shipra now. @sidntrivedi012 Please verify it with our senior project you found and clear my query.

**Comment by sidntrivedi012** [comment]
Ok @nightwarrior-xxx . Checking it .

**Comment by code-monk08** [comment]
- NLP script currently removes unnecessary punctuation from source text, 
- Tokenizes the source text to sentences, 
- makes a new file which contains clean and upper case text making it easier for further comparison with string algorithms.

**Comment by code-monk08** [comment]
I was also exploring string based algorithms through out the day, finding common strings between source and target text files is not as straight forward. 

the project which I found uses **Bloom Filters**, **Aho-Corasick Algorithm for Pattern Searching**, **Rabin Karp** all together.

I am currently understanding Aho-Corasick Algorithm, it is based on automata theory, then finally I will move to Rabin Karp, will push the python scripts for the same by midnight maybe, after which we will get head start for last task in the task list.
